name: Gatsby Publish
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: enriikke/gatsby-gh-pages-action@v2
        with:
         publishBranch: 'gh-pages'
         access-token: ${{ secrets.ACTIONS_DEPLOY_KEY }}